export interface EnhancedRecommendation {
  caseRef: string;
  product: string;
  productShort: string;
  confidencePercent: number;
  confidenceLevel: 'high' | 'medium' | 'low';
  generatedAt: string;
  engineVersion: string;
  aiAssistEnabled: boolean;
  factors: Array<{
    factor: string;
    value: string;
    impact: 'positive' | 'negative' | 'neutral';
    met: boolean;
  }>;
  alternatives: Array<{
    product: string;
    score: number;
    reason: string;
  }>;
  evidenceSources: Array<{
    source: string;
    system: string;
    timestamp: string;
    status: 'received' | 'pending' | 'error';
    contribution: string;
  }>;
  explanation: string;
  regulatoryDisclaimer: string;
}

const REGULATORY_DISCLAIMER =
  'This is an automated assessment for information purposes only. It does not constitute legal or financial advice. The applicant should seek independent money advice before making any decisions about debt solutions. This recommendation was generated by IAAS Rules Engine v2.3 and is subject to review by a qualified adviser.';

export const RECOMMENDATION_DATA: Record<string, EnhancedRecommendation> = {
  'IAAS-2026-00012': {
    caseRef: 'IAAS-2026-00012',
    product: 'Debt Arrangement Scheme (DAS)',
    productShort: 'DAS',
    confidencePercent: 94,
    confidenceLevel: 'high',
    generatedAt: '29 Jun 2026 14:35',
    engineVersion: '2.3',
    aiAssistEnabled: true,
    factors: [
      {
        factor: 'Total debt within DAS range',
        value: '£18,400 (threshold: £5,000–£250,000)',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'Disposable income sufficient',
        value: '£230/month exceeds £100 minimum threshold',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'No prior insolvency',
        value: 'Clean record — BASYS, eDEN, DAS Register all clear',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'Stable employment',
        value: 'Employed, consistent income pattern',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'Credit score acceptable',
        value: 'Score 620 (PASS) — no defaults or CCJs',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'Asset protection feasible',
        value: 'Vehicle (essential) and modest savings can be retained under DAS',
        impact: 'positive',
        met: true,
      },
    ],
    alternatives: [
      {
        product: 'Protected Trust Deed (PTD)',
        score: 71,
        reason: 'Viable but unnecessary — DAS provides full repayment without asset risk. PTD would involve trustee fees and potential asset realisation.',
      },
      {
        product: 'Sequestration',
        score: 42,
        reason: 'Disproportionate for debt level. Would damage credit record for 6 years and is not warranted given ability to repay.',
      },
      {
        product: 'Moratorium',
        score: 18,
        reason: 'Only provides temporary breathing space (6 months). Does not address underlying debt. Not a long-term solution for this case.',
      },
    ],
    evidenceSources: [
      {
        source: 'Credit Report',
        system: 'Experian',
        timestamp: '29 Jun 2026 14:33',
        status: 'received',
        contribution: 'Confirmed score 620 with clean credit history. Supports DAS eligibility.',
      },
      {
        source: 'Insolvency Register',
        system: 'BASYS',
        timestamp: '29 Jun 2026 14:33',
        status: 'received',
        contribution: 'No prior insolvency proceedings. Applicant eligible for DAS.',
      },
      {
        source: 'DAS/eDEN Register',
        system: 'eDEN',
        timestamp: '29 Jun 2026 14:34',
        status: 'received',
        contribution: 'No existing DAS arrangements. No conflict with new DAS application.',
      },
      {
        source: 'Integration Hub (4 systems)',
        system: 'Integration Hub',
        timestamp: '29 Jun 2026 14:34',
        status: 'received',
        contribution: 'CFT, Moratorium, RoI, DAS Register all clear. No blocking factors.',
      },
      {
        source: 'Income Verification',
        system: 'Self-declared',
        timestamp: '29 Jun 2026 14:25',
        status: 'received',
        contribution: 'Payslip and bank statement confirm monthly income of £2,600.',
      },
      {
        source: 'Document Verification',
        system: 'ClamAV',
        timestamp: '29 Jun 2026 14:29',
        status: 'received',
        contribution: 'All 3 uploaded documents passed virus scan and format validation.',
      },
    ],
    explanation:
      'Based on a comprehensive analysis of the applicant\'s financial circumstances, the Debt Arrangement Scheme (DAS) is the most suitable debt solution. Mr Morrison has total unsecured debts of £18,400 across four creditors, with a disposable income of £230 per month after essential expenditure. This disposable income comfortably exceeds the £100/month threshold required for a viable DAS repayment plan.\n\nA DAS would allow Mr Morrison to repay his debts in full over an extended period (approximately 80 months at current disposable income) while retaining his essential vehicle and modest savings. Creditor interest and charges would be frozen from the date of approval, and Mr Morrison would be protected from further creditor action through the statutory moratorium that accompanies an approved DAS.\n\nThis recommendation takes into account the applicant\'s stable employment, absence of prior insolvency proceedings, and the manageable ratio of debt to income. DAS is preferred over PTD as it avoids trustee involvement, protects all assets, and results in full debt repayment — which is achievable given the applicant\'s circumstances.',
    regulatoryDisclaimer: REGULATORY_DISCLAIMER,
  },
  'IAAS-2026-00011': {
    caseRef: 'IAAS-2026-00011',
    product: 'Minimal Asset Process (MAP)',
    productShort: 'MAP',
    confidencePercent: 91,
    confidenceLevel: 'high',
    generatedAt: '28 Jun 2026 09:57',
    engineVersion: '2.3',
    aiAssistEnabled: true,
    factors: [
      {
        factor: 'Total debt within MAP threshold',
        value: '£9,200 (threshold: below £25,000)',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'Low/no disposable income',
        value: '£115/month — below DAS viability threshold',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'No significant assets',
        value: 'No assets declared — meets MAP zero-asset requirement',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'Income source: benefits only',
        value: 'Universal Credit £1,100/month — meets low income criterion',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'No prior MAP application',
        value: 'Clean insolvency history — eligible for first MAP',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'Credit check adverse',
        value: 'Score 340, 2 defaults — confirms financial difficulty',
        impact: 'neutral',
        met: true,
      },
    ],
    alternatives: [
      {
        product: 'Sequestration',
        score: 55,
        reason: 'Possible but MAP is more proportionate. Sequestration typically lasts 12 months vs MAP 6 months, and involves more complex administration.',
      },
      {
        product: 'Debt Arrangement Scheme (DAS)',
        score: 28,
        reason: 'Not viable — disposable income of £115/month is below the practical threshold for meaningful debt repayment over reasonable timescale.',
      },
      {
        product: 'Debt Payment Programme (DPP)',
        score: 15,
        reason: 'Insufficient disposable income to service a DPP. Monthly payments would be nominal and extend repayment beyond 10 years.',
      },
    ],
    evidenceSources: [
      {
        source: 'Credit Report',
        system: 'Experian',
        timestamp: '28 Jun 2026 09:56',
        status: 'received',
        contribution: 'Score 340 with 2 defaults confirms financial difficulty. Supports insolvency route.',
      },
      {
        source: 'Insolvency Registers (6 systems)',
        system: 'Integration Hub',
        timestamp: '28 Jun 2026 09:57',
        status: 'received',
        contribution: 'All clear — no prior insolvency. Applicant eligible for MAP (first-time applicants only).',
      },
      {
        source: 'Benefit Verification',
        system: 'Self-declared',
        timestamp: '28 Jun 2026 09:51',
        status: 'received',
        contribution: 'Benefit letter confirms Universal Credit of £1,100/month. Meets MAP income criteria.',
      },
      {
        source: 'Asset Declaration',
        system: 'Self-declared',
        timestamp: '28 Jun 2026 09:52',
        status: 'received',
        contribution: 'No assets declared. Meets MAP requirement of no realisable assets over £2,000.',
      },
      {
        source: 'Document Verification',
        system: 'ClamAV',
        timestamp: '28 Jun 2026 09:54',
        status: 'received',
        contribution: 'Both uploaded documents passed virus scan and format validation.',
      },
      {
        source: 'Debt Verification',
        system: 'Self-declared',
        timestamp: '28 Jun 2026 09:49',
        status: 'received',
        contribution: 'Total debt £9,200 across 4 creditors. Below £25,000 MAP threshold.',
      },
    ],
    explanation:
      'The Minimal Asset Process (MAP) is recommended as the most appropriate debt solution for Ms Campbell. MAP is a simplified form of bankruptcy specifically designed for individuals with low income, minimal assets, and debts below £25,000 — all criteria that Ms Campbell meets.\n\nMs Campbell is currently unemployed and receiving Universal Credit of £1,100 per month. After essential expenditure, her disposable income is only £115/month, which is insufficient to support a meaningful debt repayment plan through DAS or a Debt Payment Programme. Her total debts of £9,200 are well within the MAP threshold of £25,000, and she has declared no assets of significant value.\n\nMAP provides a 6-month route to debt discharge with minimal administration costs (£90 application fee, which can be paid in instalments). This is the least disruptive insolvency solution available and will allow Ms Campbell to achieve a fresh financial start within 6 months, after which her debts will be discharged and she can begin rebuilding her financial position.',
    regulatoryDisclaimer: REGULATORY_DISCLAIMER,
  },
  'IAAS-2026-00010': {
    caseRef: 'IAAS-2026-00010',
    product: 'Protected Trust Deed (PTD)',
    productShort: 'PTD',
    confidencePercent: 68,
    confidenceLevel: 'medium',
    generatedAt: '26 Jun 2026 16:27',
    engineVersion: '2.3',
    aiAssistEnabled: true,
    factors: [
      {
        factor: 'Total debt significant',
        value: '£23,100 — exceeds DAS optimal range for self-employed',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'Property ownership',
        value: 'Family home with £35,000 equity — requires protection',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'Disposable income available',
        value: '£240/month supports 4-year PTD contribution period',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'No prior insolvency',
        value: 'Clean record across all registers — eligible for PTD',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'Self-employed income stability',
        value: 'Variable income pattern — only 1 year tax return provided',
        impact: 'neutral',
        met: false,
      },
      {
        factor: 'Credit score acceptable',
        value: 'Score 510 (PASS) — marginal but acceptable',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'Multiple creditor types',
        value: 'Business loan, credit card, HMRC — PTD covers all',
        impact: 'positive',
        met: true,
      },
    ],
    alternatives: [
      {
        product: 'Debt Arrangement Scheme (DAS)',
        score: 62,
        reason: 'Viable alternative but repayment would take approximately 8 years at current disposable income. Income variability as self-employed creates risk of DAS failure.',
      },
      {
        product: 'Sequestration',
        score: 38,
        reason: 'Would risk family home realisation. Disproportionate given applicant has disposable income and property equity. Should be last resort.',
      },
      {
        product: 'Minimal Asset Process (MAP)',
        score: 12,
        reason: 'Not eligible — debt exceeds threshold and applicant has significant assets (property, vehicle). MAP criteria not met.',
      },
    ],
    evidenceSources: [
      {
        source: 'Credit Report',
        system: 'Experian',
        timestamp: '26 Jun 2026 16:25',
        status: 'received',
        contribution: 'Score 510 (PASS). No defaults. Supports ability to meet PTD contribution schedule.',
      },
      {
        source: 'Insolvency Registers (6 systems)',
        system: 'Integration Hub',
        timestamp: '26 Jun 2026 16:26',
        status: 'received',
        contribution: 'All clear. No prior insolvency or trust deeds. Eligible for PTD.',
      },
      {
        source: 'Property Valuation (declared)',
        system: 'Self-declared',
        timestamp: '26 Jun 2026 16:20',
        status: 'received',
        contribution: 'Property valued at £180k with £145k mortgage. £35k equity — significant factor in PTD vs sequestration decision.',
      },
      {
        source: 'Tax Return 2025',
        system: 'Self-declared',
        timestamp: '26 Jun 2026 16:22',
        status: 'received',
        contribution: 'Self-employed income shown as £2,200/month average. Only 1 year provided — additional verification requested.',
      },
      {
        source: 'Bank Statements',
        system: 'Pending',
        timestamp: '28 Jun 2026 11:30',
        status: 'pending',
        contribution: 'Requested: 3 months business and personal bank statements to verify income stability.',
      },
      {
        source: 'Document Verification',
        system: 'ClamAV',
        timestamp: '26 Jun 2026 16:22',
        status: 'received',
        contribution: 'Tax return document passed virus scan and format validation.',
      },
    ],
    explanation:
      'A Protected Trust Deed (PTD) is recommended as the most suitable debt solution for Mr Stewart. With total debts of £23,100 and a family home with £35,000 equity, the primary consideration is protecting the property while achieving meaningful debt resolution. A PTD allows the applicant to retain their home provided they maintain agreed contributions over the 4-year trust deed period.\n\nMr Stewart\'s disposable income of £240/month would translate to total contributions of approximately £11,520 over 48 months. While this represents less than full repayment of the £23,100 debt, a PTD allows for partial settlement with creditor agreement, typically at 70-80% of the debt value when combined with the trustee\'s management of non-essential assets.\n\nThe confidence level is medium (68%) rather than high due to the applicant\'s self-employed status. Self-employed income can be variable, and only one year of tax returns has been provided. Additional bank statements have been requested to verify income stability over recent months. If income is confirmed as stable, confidence would increase. The assigned adviser should review the additional documentation before proceeding with a formal PTD recommendation to the applicant.',
    regulatoryDisclaimer: REGULATORY_DISCLAIMER,
  },
  'IAAS-2026-00009': {
    caseRef: 'IAAS-2026-00009',
    product: 'Sequestration (Bankruptcy)',
    productShort: 'Sequestration',
    confidencePercent: 61,
    confidenceLevel: 'medium',
    generatedAt: '25 Jun 2026 11:35',
    engineVersion: '2.3',
    aiAssistEnabled: true,
    factors: [
      {
        factor: 'Previous insolvency history',
        value: 'Prior sequestration (2015–2018) found in BASYS — manual review required',
        impact: 'negative',
        met: false,
      },
      {
        factor: 'No significant assets',
        value: 'No assets declared — no barriers to sequestration',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'Low income (pension + benefits)',
        value: '£880/month total income — limited repayment capacity',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'Credit check adverse',
        value: 'Score 280 (FAIL), 1 CCJ — confirms financial difficulty',
        impact: 'positive',
        met: true,
      },
      {
        factor: 'Debt level manageable',
        value: '£6,800 total — relatively low, but no capacity to repay',
        impact: 'neutral',
        met: true,
      },
      {
        factor: 'No existing insolvency arrangements',
        value: 'Previous sequestration fully discharged — no active proceedings',
        impact: 'positive',
        met: true,
      },
    ],
    alternatives: [
      {
        product: 'Minimal Asset Process (MAP)',
        score: 52,
        reason: 'Meets most MAP criteria (low income, no assets, debt under £25k) but MAP is only available to first-time applicants. Previous sequestration may disqualify — requires manual verification of MAP eligibility rules.',
      },
      {
        product: 'Debt Arrangement Scheme (DAS)',
        score: 35,
        reason: 'Disposable income of £265/month technically meets DAS threshold, but debt-to-income ratio and CCJ suggest ongoing financial difficulty. DAS may not be sustainable long-term.',
      },
      {
        product: 'Signposting to Money Advice',
        score: 25,
        reason: 'Given previous insolvency and complexity of case, applicant would benefit from independent money advice before proceeding with any formal solution.',
      },
    ],
    evidenceSources: [
      {
        source: 'Credit Report',
        system: 'Experian',
        timestamp: '25 Jun 2026 11:33',
        status: 'received',
        contribution: 'Score 280 with 1 CCJ. Confirms severe financial difficulty and supports insolvency route.',
      },
      {
        source: 'BASYS Register',
        system: 'BASYS',
        timestamp: '25 Jun 2026 11:34',
        status: 'received',
        contribution: 'Previous sequestration found: SEQ-2015-04821 (awarded 2015, discharged 2018). Critical factor — affects product eligibility.',
      },
      {
        source: 'eDEN/DAS/CFT/Moratorium/RoI',
        system: 'Integration Hub',
        timestamp: '25 Jun 2026 11:34',
        status: 'received',
        contribution: 'All clear. No other active insolvency arrangements. Previous case fully discharged.',
      },
      {
        source: 'Income Declaration',
        system: 'Self-declared',
        timestamp: '25 Jun 2026 11:30',
        status: 'received',
        contribution: 'State pension £680/month + benefits £200/month. Fixed income with no prospect of increase.',
      },
      {
        source: 'Asset Declaration',
        system: 'Self-declared',
        timestamp: '25 Jun 2026 11:31',
        status: 'received',
        contribution: 'No assets declared. Applicant is a council tenant with no vehicle or savings.',
      },
      {
        source: 'Supporting Documents',
        system: 'N/A',
        timestamp: '25 Jun 2026 11:33',
        status: 'pending',
        contribution: 'No documents uploaded. Adviser may request pension statement and benefit award letter.',
      },
    ],
    explanation:
      'Sequestration (bankruptcy) is recommended as the most appropriate debt solution for Mrs Murray, though with medium confidence due to the complexity introduced by her previous sequestration. Mrs Murray was previously sequestrated in 2015 and discharged in 2018. While a second sequestration is legally permissible in Scotland, it requires careful consideration and typically attracts greater scrutiny from the Accountant in Bankruptcy.\n\nMrs Murray\'s current financial position shows total debts of £6,800 with a combined income of £880/month from state pension and benefits. After essential expenditure, her disposable income is £265/month. While this technically supports a DAS arrangement, the presence of a CCJ and the applicant\'s age and fixed income suggest that a formal insolvency solution providing a clean break would be more appropriate and sustainable.\n\nThe Minimal Asset Process (MAP) would normally be the preferred route for someone with Mrs Murray\'s financial profile, but MAP eligibility may be restricted for applicants with a previous sequestration. This requires manual verification by a qualified adviser. The recommendation is flagged for priority senior adviser review to determine whether MAP or full sequestration is the appropriate route forward.',
    regulatoryDisclaimer: REGULATORY_DISCLAIMER,
  },
};
