'use client';

export default function PdfExport({ caseRef, product, confidence }: { caseRef: string; product: string; confidence: number }) {
  const generatePdf = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <html>
      <head>
        <title>IAAS Recommendation Report — ${caseRef}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
          .header { border-bottom: 3px solid #d32205; padding-bottom: 20px; margin-bottom: 30px; }
          .logo { font-size: 24px; font-weight: bold; color: #d32205; }
          .subtitle { color: #666; font-size: 14px; }
          h1 { font-size: 22px; margin-top: 30px; }
          h2 { font-size: 16px; color: #333; border-bottom: 1px solid #ddd; padding-bottom: 8px; }
          .confidence { font-size: 36px; font-weight: bold; color: #00703c; }
          .factors { margin: 20px 0; }
          .factor { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #eee; }
          .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 11px; color: #666; }
          .badge { background: #00703c; color: white; padding: 4px 12px; border-radius: 4px; font-size: 12px; }
          table { width: 100%; border-collapse: collapse; margin: 15px 0; }
          td, th { padding: 8px; border: 1px solid #ddd; text-align: left; font-size: 13px; }
          th { background: #f5f5f5; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">Accountant in Bankruptcy</div>
          <div class="subtitle">Initial Application Advice Service — Recommendation Report</div>
        </div>

        <h1>Recommendation Report</h1>
        <p><strong>Case Reference:</strong> ${caseRef}</p>
        <p><strong>Generated:</strong> ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
        <p><strong>Engine:</strong> Rules v2.3 • AI Assist Enabled</p>

        <h2>Recommendation</h2>
        <p style="font-size: 20px; font-weight: bold;">${product}</p>
        <p>Confidence: <span class="confidence">${confidence}%</span></p>

        <h2>Decision Factors</h2>
        <table>
          <tr><th>Factor</th><th>Value</th><th>Impact</th></tr>
          <tr><td>Debt Level</td><td>£18,400</td><td>✓ Positive</td></tr>
          <tr><td>Disposable Income</td><td>£230/month</td><td>✓ Positive</td></tr>
          <tr><td>Employment Status</td><td>Employed</td><td>✓ Positive</td></tr>
          <tr><td>No Prior Insolvency</td><td>Confirmed</td><td>✓ Positive</td></tr>
          <tr><td>Credit Score</td><td>620 (PASS)</td><td>✓ Positive</td></tr>
        </table>

        <h2>Alternatives Considered</h2>
        <table>
          <tr><th>Product</th><th>Score</th><th>Reason Not Selected</th></tr>
          <tr><td>Protected Trust Deed</td><td>71%</td><td>DAS preferred given repayment capacity</td></tr>
          <tr><td>Sequestration</td><td>42%</td><td>Applicant can service debt</td></tr>
          <tr><td>Moratorium</td><td>18%</td><td>No immediate crisis</td></tr>
        </table>

        <h2>Evidence Sources</h2>
        <table>
          <tr><th>Source</th><th>System</th><th>Status</th></tr>
          <tr><td>Applicant Declaration</td><td>IAAS</td><td>✓ Received</td></tr>
          <tr><td>Experian Credit Bureau</td><td>Credit Check</td><td>✓ Received</td></tr>
          <tr><td>BASYS Register</td><td>BASYS</td><td>✓ Clear</td></tr>
          <tr><td>eDEN/DASH</td><td>eDEN</td><td>✓ Clear</td></tr>
          <tr><td>DAS Register</td><td>DAS</td><td>✓ Clear</td></tr>
          <tr><td>Register of Insolvencies</td><td>RoI</td><td>✓ Clear</td></tr>
        </table>

        <div class="footer">
          <p><strong>Disclaimer:</strong> This is an automated assessment for information purposes only. It does not constitute legal or financial advice. The applicant should seek independent money advice before making any decisions about debt solutions.</p>
          <p>Generated by IAAS Rules Engine v2.3 • Accountant in Bankruptcy • Scottish Government</p>
          <p>Document ID: RPT-${caseRef}-${Date.now()}</p>
        </div>
      </body>
      </html>
    `);
    printWindow.document.close();
    // Small delay to ensure content renders before print dialog
    setTimeout(() => { printWindow.print(); }, 500);
  };

  return (
    // Demo mode highlights this button but never clicks it — generatePdf opens a
    // popup and calls print(), and a modal print dialog stalls the demo player.
    <button onClick={generatePdf} data-demo="recommendation-pdf" className="inline-flex items-center gap-2 bg-blue-700 hover:bg-blue-800 text-white font-bold px-4 py-2 rounded text-sm print:hidden">
      📄 Download PDF Report
    </button>
  );
}
