export interface SeedApplication {
  ref: string;
  firstName: string;
  lastName: string;
  status: string;
  debt: number;
  product: string;
  date: string;
  ni: string;
  source: string;
  postcode: string;
  email: string;
  employment: string;
  confidence: number;
  assignedTo: string;
  city: string;
}

export const seedApplications: SeedApplication[] = [
  { ref: "IAAS-2026-00001", firstName: "Alistair", lastName: "Morrison", status: "approved", debt: 14500, product: "DAS", date: "2026-06-02", ni: "SC123456A", source: "BASYS", postcode: "EH1 2AB", email: "alistair.morrison@email.co.uk", employment: "employed", confidence: 87, assignedTo: "Karen MacLeod", city: "Edinburgh" },
  { ref: "IAAS-2026-00002", firstName: "Fiona", lastName: "Campbell", status: "submitted", debt: 8200, product: "MAP", date: "2026-06-03", ni: "SC234567B", source: "eDEN", postcode: "G1 3CD", email: "fiona.campbell@email.co.uk", employment: "employed", confidence: 92, assignedTo: "Unassigned", city: "Glasgow" },
  { ref: "IAAS-2026-00003", firstName: "Craig", lastName: "Stewart", status: "approved", debt: 22000, product: "DAS", date: "2026-06-04", ni: "SC345678C", source: "DAS", postcode: "AB10 1EF", email: "craig.stewart@email.co.uk", employment: "self_employed", confidence: 78, assignedTo: "James Wilson", city: "Aberdeen" },
  { ref: "IAAS-2026-00004", firstName: "Heather", lastName: "Murray", status: "under_review", debt: 5600, product: "Signposting", date: "2026-06-05", ni: "SC456789D", source: "IAAS", postcode: "DD1 4GH", email: "heather.murray@email.co.uk", employment: "unemployed", confidence: 65, assignedTo: "Sarah Mitchell", city: "Dundee" },
  { ref: "IAAS-2026-00005", firstName: "Kenneth", lastName: "MacDonald", status: "draft", debt: 31000, product: "Sequestration", date: "2026-06-06", ni: "SC567890E", source: "BASYS", postcode: "FK1 2JK", email: "kenneth.macdonald@email.co.uk", employment: "employed", confidence: 71, assignedTo: "Unassigned", city: "Falkirk" },
  { ref: "IAAS-2026-00006", firstName: "Janet", lastName: "Henderson", status: "approved", debt: 18900, product: "DAS", date: "2026-06-07", ni: "SC678901F", source: "DAS", postcode: "PH1 5LM", email: "janet.henderson@email.co.uk", employment: "employed", confidence: 94, assignedTo: "Karen MacLeod", city: "Perth" },
  { ref: "IAAS-2026-00007", firstName: "Graeme", lastName: "Robertson", status: "rejected", debt: 2100, product: "DPP", date: "2026-06-08", ni: "SC789012G", source: "eDEN", postcode: "IV1 1NP", email: "graeme.robertson@email.co.uk", employment: "retired", confidence: 62, assignedTo: "James Wilson", city: "Inverness" },
  { ref: "IAAS-2026-00008", firstName: "Eleanor", lastName: "Wilson", status: "submitted", debt: 12400, product: "PTD", date: "2026-06-09", ni: "SC890123H", source: "BASYS", postcode: "KA1 3QR", email: "eleanor.wilson@email.co.uk", employment: "employed", confidence: 83, assignedTo: "Unassigned", city: "Kilmarnock" },
  { ref: "IAAS-2026-00009", firstName: "Malcolm", lastName: "Thomson", status: "approved", debt: 27500, product: "DAS", date: "2026-06-10", ni: "SC901234J", source: "DAS", postcode: "PA1 2ST", email: "malcolm.thomson@email.co.uk", employment: "self_employed", confidence: 89, assignedTo: "Sarah Mitchell", city: "Paisley" },
  { ref: "IAAS-2026-00010", firstName: "Brenda", lastName: "Anderson", status: "additional_info_required", debt: 9800, product: "MAP", date: "2026-06-11", ni: "SC012345K", source: "IAAS", postcode: "EH3 6UV", email: "brenda.anderson@email.co.uk", employment: "unemployed", confidence: 74, assignedTo: "Karen MacLeod", city: "Edinburgh" },
  { ref: "IAAS-2026-00011", firstName: "Iain", lastName: "MacLeod", status: "approved", debt: 35000, product: "Sequestration", date: "2026-06-12", ni: "SC113456L", source: "BASYS", postcode: "G12 8WX", email: "iain.macleod@email.co.uk", employment: "unemployed", confidence: 91, assignedTo: "James Wilson", city: "Glasgow" },
  { ref: "IAAS-2026-00012", firstName: "Diana", lastName: "Fraser", status: "draft", debt: 4300, product: "Signposting", date: "2026-06-13", ni: "SC224567M", source: "eDEN", postcode: "KY1 1YZ", email: "diana.fraser@email.co.uk", employment: "retired", confidence: 68, assignedTo: "Unassigned", city: "Dunfermline" },
  { ref: "IAAS-2026-00013", firstName: "Robert", lastName: "Ross", status: "under_review", debt: 16700, product: "DAS", date: "2026-06-14", ni: "SC335678N", source: "DAS", postcode: "EH7 4AB", email: "robert.ross@email.co.uk", employment: "employed", confidence: 85, assignedTo: "Sarah Mitchell", city: "Edinburgh" },
  { ref: "IAAS-2026-00014", firstName: "Nicola", lastName: "Grant", status: "submitted", debt: 21300, product: "DAS", date: "2026-06-15", ni: "SC446789P", source: "BASYS", postcode: "G41 2CD", email: "nicola.grant@email.co.uk", employment: "employed", confidence: 79, assignedTo: "Unassigned", city: "Glasgow" },
  { ref: "IAAS-2026-00015", firstName: "Thomas", lastName: "Hamilton", status: "approved", debt: 11800, product: "PTD", date: "2026-06-16", ni: "SC557890Q", source: "IAAS", postcode: "AB11 5EF", email: "thomas.hamilton@email.co.uk", employment: "employed", confidence: 96, assignedTo: "Karen MacLeod", city: "Aberdeen" },
  { ref: "IAAS-2026-00016", firstName: "Sheila", lastName: "Wallace", status: "rejected", debt: 1200, product: "DPP", date: "2026-06-17", ni: "SC668901R", source: "eDEN", postcode: "DD2 6GH", email: "sheila.wallace@email.co.uk", employment: "retired", confidence: 61, assignedTo: "James Wilson", city: "Dundee" },
  { ref: "IAAS-2026-00017", firstName: "Owen", lastName: "Douglas", status: "approved", debt: 19400, product: "DAS", date: "2026-06-18", ni: "SC779012S", source: "DAS", postcode: "FK2 7JK", email: "owen.douglas@email.co.uk", employment: "self_employed", confidence: 88, assignedTo: "Sarah Mitchell", city: "Falkirk" },
  { ref: "IAAS-2026-00018", firstName: "Linda", lastName: "Burns", status: "under_review", debt: 7400, product: "MAP", date: "2026-06-19", ni: "SC880123T", source: "BASYS", postcode: "EH10 5LM", email: "linda.burns@email.co.uk", employment: "unemployed", confidence: 72, assignedTo: "Karen MacLeod", city: "Edinburgh" },
  { ref: "IAAS-2026-00019", firstName: "Craig", lastName: "Scott", status: "draft", debt: 42000, product: "Sequestration", date: "2026-06-20", ni: "SC991234U", source: "IAAS", postcode: "G3 7NP", email: "craig.scott@email.co.uk", employment: "unemployed", confidence: 76, assignedTo: "Unassigned", city: "Glasgow" },
  { ref: "IAAS-2026-00020", firstName: "Patricia", lastName: "MacKenzie", status: "approved", debt: 15600, product: "DAS", date: "2026-06-21", ni: "SC102345V", source: "eDEN", postcode: "PH2 8QR", email: "patricia.mackenzie@email.co.uk", employment: "employed", confidence: 93, assignedTo: "James Wilson", city: "Perth" },
  { ref: "IAAS-2026-00021", firstName: "Alistair", lastName: "Sinclair", status: "submitted", debt: 28900, product: "PTD", date: "2026-06-22", ni: "SC213456W", source: "BASYS", postcode: "IV2 3ST", email: "alistair.sinclair@email.co.uk", employment: "employed", confidence: 81, assignedTo: "Unassigned", city: "Inverness" },
  { ref: "IAAS-2026-00022", firstName: "Fiona", lastName: "Reid", status: "additional_info_required", debt: 6100, product: "DPP", date: "2026-06-23", ni: "SC324567X", source: "DAS", postcode: "KA3 4UV", email: "fiona.reid@email.co.uk", employment: "employed", confidence: 69, assignedTo: "Sarah Mitchell", city: "Kilmarnock" },
  { ref: "IAAS-2026-00023", firstName: "Graeme", lastName: "Patterson", status: "approved", debt: 33500, product: "DAS", date: "2026-06-24", ni: "SC435678Y", source: "BASYS", postcode: "EH12 7WX", email: "graeme.patterson@email.co.uk", employment: "self_employed", confidence: 90, assignedTo: "Karen MacLeod", city: "Edinburgh" },
  { ref: "IAAS-2026-00024", firstName: "Heather", lastName: "Young", status: "rejected", debt: 3800, product: "Signposting", date: "2026-06-25", ni: "SC546789Z", source: "IAAS", postcode: "G51 1YZ", email: "heather.young@email.co.uk", employment: "retired", confidence: 63, assignedTo: "Unassigned", city: "Glasgow" },
  { ref: "IAAS-2026-00025", firstName: "Kenneth", lastName: "Mitchell", status: "under_review", debt: 17200, product: "DAS", date: "2026-06-26", ni: "SC657890A", source: "eDEN", postcode: "AB15 4AB", email: "kenneth.mitchell@email.co.uk", employment: "employed", confidence: 86, assignedTo: "James Wilson", city: "Aberdeen" },
  { ref: "IAAS-2026-00026", firstName: "Janet", lastName: "Clark", status: "approved", debt: 24800, product: "MAP", date: "2026-06-27", ni: "SC768901B", source: "DAS", postcode: "DD3 5CD", email: "janet.clark@email.co.uk", employment: "employed", confidence: 95, assignedTo: "Sarah Mitchell", city: "Dundee" },
  { ref: "IAAS-2026-00027", firstName: "Malcolm", lastName: "Brown", status: "submitted", debt: 10500, product: "DAS", date: "2026-06-28", ni: "SC879012C", source: "BASYS", postcode: "FK3 6EF", email: "malcolm.brown@email.co.uk", employment: "unemployed", confidence: 77, assignedTo: "Unassigned", city: "Falkirk" },
  { ref: "IAAS-2026-00028", firstName: "Eleanor", lastName: "MacPherson", status: "draft", debt: 8900, product: "DPP", date: "2026-06-29", ni: "SC980123D", source: "IAAS", postcode: "PA2 7GH", email: "eleanor.macpherson@email.co.uk", employment: "unemployed", confidence: 66, assignedTo: "Unassigned", city: "Paisley" },
  { ref: "IAAS-2026-00029", firstName: "Iain", lastName: "Duncan", status: "approved", debt: 20100, product: "PTD", date: "2026-06-30", ni: "SC091234E", source: "eDEN", postcode: "EH4 8JK", email: "iain.duncan@email.co.uk", employment: "employed", confidence: 84, assignedTo: "Karen MacLeod", city: "Edinburgh" },
  { ref: "IAAS-2026-00030", firstName: "Diana", lastName: "Kerr", status: "under_review", debt: 13600, product: "DAS", date: "2026-07-01", ni: "SC102346F", source: "BASYS", postcode: "G20 9LM", email: "diana.kerr@email.co.uk", employment: "self_employed", confidence: 82, assignedTo: "James Wilson", city: "Glasgow" },
  { ref: "IAAS-2026-00031", firstName: "Robert", lastName: "Johnston", status: "approved", debt: 38000, product: "Sequestration", date: "2026-07-02", ni: "SC213457G", source: "DAS", postcode: "KY2 2NP", email: "robert.johnston@email.co.uk", employment: "unemployed", confidence: 73, assignedTo: "Sarah Mitchell", city: "Dunfermline" },
  { ref: "IAAS-2026-00032", firstName: "Nicola", lastName: "Morrison", status: "submitted", debt: 6800, product: "MAP", date: "2026-07-02", ni: "SC324568H", source: "IAAS", postcode: "EH15 1QR", email: "nicola.morrison@email.co.uk", employment: "employed", confidence: 88, assignedTo: "Unassigned", city: "Edinburgh" },
  { ref: "IAAS-2026-00033", firstName: "Thomas", lastName: "Campbell", status: "additional_info_required", debt: 15200, product: "DAS", date: "2026-07-03", ni: "SC435679J", source: "BASYS", postcode: "G4 2ST", email: "thomas.campbell@email.co.uk", employment: "employed", confidence: 75, assignedTo: "Karen MacLeod", city: "Glasgow" },
  { ref: "IAAS-2026-00034", firstName: "Sheila", lastName: "Stewart", status: "approved", debt: 9300, product: "DPP", date: "2026-07-04", ni: "SC546780K", source: "eDEN", postcode: "AB12 3UV", email: "sheila.stewart@email.co.uk", employment: "retired", confidence: 91, assignedTo: "James Wilson", city: "Aberdeen" },
  { ref: "IAAS-2026-00035", firstName: "Owen", lastName: "Murray", status: "draft", debt: 26700, product: "DAS", date: "2026-07-05", ni: "SC657891L", source: "DAS", postcode: "DD4 4WX", email: "owen.murray@email.co.uk", employment: "employed", confidence: 80, assignedTo: "Unassigned", city: "Dundee" },
  { ref: "IAAS-2026-00036", firstName: "Linda", lastName: "MacDonald", status: "rejected", debt: 2800, product: "Signposting", date: "2026-07-06", ni: "SC768902M", source: "BASYS", postcode: "FK4 5YZ", email: "linda.macdonald@email.co.uk", employment: "unemployed", confidence: 64, assignedTo: "Unassigned", city: "Falkirk" },
  { ref: "IAAS-2026-00037", firstName: "Craig", lastName: "Henderson", status: "under_review", debt: 19800, product: "PTD", date: "2026-07-07", ni: "SC879013N", source: "IAAS", postcode: "PH3 1AB", email: "craig.henderson@email.co.uk", employment: "employed", confidence: 87, assignedTo: "Sarah Mitchell", city: "Perth" },
  { ref: "IAAS-2026-00038", firstName: "Patricia", lastName: "Robertson", status: "approved", debt: 11200, product: "DAS", date: "2026-07-08", ni: "SC980124P", source: "eDEN", postcode: "IV3 5CD", email: "patricia.robertson@email.co.uk", employment: "employed", confidence: 93, assignedTo: "Karen MacLeod", city: "Inverness" },
  { ref: "IAAS-2026-00039", firstName: "Alistair", lastName: "Wilson", status: "submitted", debt: 44000, product: "Sequestration", date: "2026-07-09", ni: "SC091235Q", source: "BASYS", postcode: "KA4 6EF", email: "alistair.wilson@email.co.uk", employment: "unemployed", confidence: 70, assignedTo: "Unassigned", city: "Kilmarnock" },
  { ref: "IAAS-2026-00040", firstName: "Fiona", lastName: "Thomson", status: "approved", debt: 16300, product: "MAP", date: "2026-07-10", ni: "SC102347R", source: "DAS", postcode: "EH6 7GH", email: "fiona.thomson@email.co.uk", employment: "self_employed", confidence: 89, assignedTo: "James Wilson", city: "Edinburgh" },
  { ref: "IAAS-2026-00041", firstName: "Graeme", lastName: "Anderson", status: "under_review", debt: 7900, product: "DAS", date: "2026-07-11", ni: "SC213458S", source: "BASYS", postcode: "G61 2JK", email: "graeme.anderson@email.co.uk", employment: "employed", confidence: 76, assignedTo: "Sarah Mitchell", city: "Glasgow" },
  { ref: "IAAS-2026-00042", firstName: "Heather", lastName: "MacLeod", status: "draft", debt: 3500, product: "DPP", date: "2026-07-11", ni: "SC324569T", source: "IAAS", postcode: "PA3 8LM", email: "heather.macleod@email.co.uk", employment: "retired", confidence: 67, assignedTo: "Unassigned", city: "Paisley" },
  { ref: "IAAS-2026-00043", firstName: "Kenneth", lastName: "Fraser", status: "approved", debt: 29400, product: "DAS", date: "2026-07-12", ni: "SC435680U", source: "eDEN", postcode: "KY3 9NP", email: "kenneth.fraser@email.co.uk", employment: "employed", confidence: 95, assignedTo: "Karen MacLeod", city: "Dunfermline" },
  { ref: "IAAS-2026-00044", firstName: "Janet", lastName: "Ross", status: "submitted", debt: 13100, product: "PTD", date: "2026-07-13", ni: "SC546781V", source: "DAS", postcode: "EH9 3QR", email: "janet.ross@email.co.uk", employment: "employed", confidence: 83, assignedTo: "Unassigned", city: "Edinburgh" },
  { ref: "IAAS-2026-00045", firstName: "Malcolm", lastName: "Grant", status: "additional_info_required", debt: 21800, product: "DAS", date: "2026-07-14", ni: "SC657892W", source: "BASYS", postcode: "G73 4ST", email: "malcolm.grant@email.co.uk", employment: "self_employed", confidence: 74, assignedTo: "James Wilson", city: "Glasgow" },
  { ref: "IAAS-2026-00046", firstName: "Eleanor", lastName: "Hamilton", status: "rejected", debt: 1800, product: "Signposting", date: "2026-07-15", ni: "SC768903X", source: "IAAS", postcode: "AB16 5UV", email: "eleanor.hamilton@email.co.uk", employment: "unemployed", confidence: 62, assignedTo: "Unassigned", city: "Aberdeen" },
  { ref: "IAAS-2026-00047", firstName: "Iain", lastName: "Wallace", status: "approved", debt: 17800, product: "DAS", date: "2026-07-16", ni: "SC879014Y", source: "BASYS", postcode: "DD5 6WX", email: "iain.wallace@email.co.uk", employment: "employed", confidence: 90, assignedTo: "Sarah Mitchell", city: "Dundee" },
  { ref: "IAAS-2026-00048", firstName: "Diana", lastName: "Douglas", status: "under_review", debt: 8600, product: "MAP", date: "2026-07-17", ni: "SC980125Z", source: "eDEN", postcode: "FK5 7YZ", email: "diana.douglas@email.co.uk", employment: "employed", confidence: 78, assignedTo: "Karen MacLeod", city: "Falkirk" },
  { ref: "IAAS-2026-00049", firstName: "Robert", lastName: "Burns", status: "approved", debt: 36500, product: "Sequestration", date: "2026-07-18", ni: "SC091236A", source: "DAS", postcode: "EH11 1AB", email: "robert.burns@email.co.uk", employment: "unemployed", confidence: 85, assignedTo: "James Wilson", city: "Edinburgh" },
  { ref: "IAAS-2026-00050", firstName: "Nicola", lastName: "Scott", status: "submitted", debt: 10900, product: "DAS", date: "2026-07-19", ni: "SC102348B", source: "BASYS", postcode: "G78 2CD", email: "nicola.scott@email.co.uk", employment: "employed", confidence: 82, assignedTo: "Unassigned", city: "Glasgow" },
  { ref: "IAAS-2026-00051", firstName: "Thomas", lastName: "MacKenzie", status: "draft", debt: 5200, product: "DPP", date: "2026-07-20", ni: "SC213459C", source: "IAAS", postcode: "PH1 3EF", email: "thomas.mackenzie@email.co.uk", employment: "retired", confidence: 66, assignedTo: "Unassigned", city: "Perth" },
  { ref: "IAAS-2026-00052", firstName: "Sheila", lastName: "Sinclair", status: "approved", debt: 23400, product: "DAS", date: "2026-07-20", ni: "SC324570D", source: "eDEN", postcode: "IV1 4GH", email: "sheila.sinclair@email.co.uk", employment: "employed", confidence: 97, assignedTo: "Sarah Mitchell", city: "Inverness" },
  { ref: "IAAS-2026-00053", firstName: "Owen", lastName: "Reid", status: "under_review", debt: 14100, product: "PTD", date: "2026-07-21", ni: "SC435681E", source: "BASYS", postcode: "KA5 5JK", email: "owen.reid@email.co.uk", employment: "employed", confidence: 81, assignedTo: "Karen MacLeod", city: "Kilmarnock" },
  { ref: "IAAS-2026-00054", firstName: "Linda", lastName: "Patterson", status: "additional_info_required", debt: 7100, product: "MAP", date: "2026-07-22", ni: "SC546782F", source: "DAS", postcode: "PA4 6LM", email: "linda.patterson@email.co.uk", employment: "unemployed", confidence: 71, assignedTo: "Unassigned", city: "Paisley" },
  { ref: "IAAS-2026-00055", firstName: "Craig", lastName: "Young", status: "approved", debt: 18500, product: "DAS", date: "2026-07-23", ni: "SC657893G", source: "BASYS", postcode: "KY4 7NP", email: "craig.young@email.co.uk", employment: "employed", confidence: 92, assignedTo: "James Wilson", city: "Dunfermline" },
  { ref: "IAAS-2026-00056", firstName: "Patricia", lastName: "Mitchell", status: "rejected", debt: 2400, product: "Signposting", date: "2026-07-24", ni: "SC768904H", source: "IAAS", postcode: "EH14 8QR", email: "patricia.mitchell@email.co.uk", employment: "unemployed", confidence: 63, assignedTo: "Unassigned", city: "Edinburgh" },
  { ref: "IAAS-2026-00057", firstName: "Alistair", lastName: "Clark", status: "submitted", debt: 25600, product: "DAS", date: "2026-07-25", ni: "SC879015J", source: "eDEN", postcode: "G11 9ST", email: "alistair.clark@email.co.uk", employment: "employed", confidence: 86, assignedTo: "Unassigned", city: "Glasgow" },
  { ref: "IAAS-2026-00058", firstName: "Fiona", lastName: "Brown", status: "approved", debt: 12700, product: "MAP", date: "2026-07-25", ni: "SC980126K", source: "DAS", postcode: "AB17 1UV", email: "fiona.brown@email.co.uk", employment: "employed", confidence: 94, assignedTo: "Sarah Mitchell", city: "Aberdeen" },
  { ref: "IAAS-2026-00059", firstName: "Graeme", lastName: "MacPherson", status: "under_review", debt: 40000, product: "Sequestration", date: "2026-07-26", ni: "SC091237L", source: "BASYS", postcode: "DD1 2WX", email: "graeme.macpherson@email.co.uk", employment: "unemployed", confidence: 73, assignedTo: "Karen MacLeod", city: "Dundee" },
  { ref: "IAAS-2026-00060", firstName: "Heather", lastName: "Duncan", status: "draft", debt: 4800, product: "Signposting", date: "2026-07-27", ni: "SC102349M", source: "IAAS", postcode: "FK6 3YZ", email: "heather.duncan@email.co.uk", employment: "retired", confidence: 65, assignedTo: "Unassigned", city: "Falkirk" },
  { ref: "IAAS-2026-00061", firstName: "Kenneth", lastName: "Kerr", status: "approved", debt: 16900, product: "DAS", date: "2026-07-28", ni: "SC213460N", source: "eDEN", postcode: "EH2 4AB", email: "kenneth.kerr@email.co.uk", employment: "self_employed", confidence: 88, assignedTo: "James Wilson", city: "Edinburgh" },
  { ref: "IAAS-2026-00062", firstName: "Janet", lastName: "Johnston", status: "submitted", debt: 9500, product: "DPP", date: "2026-07-28", ni: "SC324571P", source: "BASYS", postcode: "G32 5CD", email: "janet.johnston@email.co.uk", employment: "employed", confidence: 79, assignedTo: "Unassigned", city: "Glasgow" },
  { ref: "IAAS-2026-00063", firstName: "Malcolm", lastName: "Morrison", status: "additional_info_required", debt: 22500, product: "PTD", date: "2026-07-29", ni: "SC435682Q", source: "DAS", postcode: "AB20 6EF", email: "malcolm.morrison@email.co.uk", employment: "employed", confidence: 75, assignedTo: "Sarah Mitchell", city: "Aberdeen" },
  { ref: "IAAS-2026-00064", firstName: "Eleanor", lastName: "Campbell", status: "approved", debt: 14800, product: "DAS", date: "2026-07-30", ni: "SC546783R", source: "BASYS", postcode: "PH2 7GH", email: "eleanor.campbell@email.co.uk", employment: "employed", confidence: 91, assignedTo: "Karen MacLeod", city: "Perth" },
  { ref: "IAAS-2026-00065", firstName: "Iain", lastName: "Stewart", status: "rejected", debt: 3200, product: "Signposting", date: "2026-07-31", ni: "SC657894S", source: "IAAS", postcode: "IV2 8JK", email: "iain.stewart@email.co.uk", employment: "unemployed", confidence: 61, assignedTo: "Unassigned", city: "Inverness" },
  { ref: "IAAS-2026-00066", firstName: "Diana", lastName: "Murray", status: "under_review", debt: 11600, product: "DAS", date: "2026-07-31", ni: "SC768905T", source: "eDEN", postcode: "KA6 9LM", email: "diana.murray@email.co.uk", employment: "employed", confidence: 84, assignedTo: "James Wilson", city: "Kilmarnock" },
  { ref: "IAAS-2026-00067", firstName: "Robert", lastName: "MacDonald", status: "draft", debt: 47500, product: "Sequestration", date: "2026-08-01", ni: "SC879016U", source: "BASYS", postcode: "PA5 1NP", email: "robert.macdonald@email.co.uk", employment: "unemployed", confidence: 69, assignedTo: "Unassigned", city: "Paisley" },
  { ref: "IAAS-2026-00068", firstName: "Nicola", lastName: "Henderson", status: "approved", debt: 19100, product: "DAS", date: "2026-08-01", ni: "SC980127V", source: "DAS", postcode: "KY5 2QR", email: "nicola.henderson@email.co.uk", employment: "employed", confidence: 96, assignedTo: "Sarah Mitchell", city: "Dunfermline" },
  { ref: "IAAS-2026-00069", firstName: "Thomas", lastName: "Robertson", status: "submitted", debt: 8100, product: "MAP", date: "2026-08-02", ni: "SC091238W", source: "BASYS", postcode: "EH5 3ST", email: "thomas.robertson@email.co.uk", employment: "self_employed", confidence: 77, assignedTo: "Unassigned", city: "Edinburgh" },
  { ref: "IAAS-2026-00070", firstName: "Sheila", lastName: "Wilson", status: "additional_info_required", debt: 6500, product: "DPP", date: "2026-08-02", ni: "SC102350X", source: "eDEN", postcode: "G5 4UV", email: "sheila.wilson@email.co.uk", employment: "retired", confidence: 70, assignedTo: "Karen MacLeod", city: "Glasgow" },
  { ref: "IAAS-2026-00071", firstName: "Owen", lastName: "Thomson", status: "approved", debt: 30200, product: "DAS", date: "2026-08-03", ni: "SC213461Y", source: "DAS", postcode: "AB21 5WX", email: "owen.thomson@email.co.uk", employment: "employed", confidence: 89, assignedTo: "James Wilson", city: "Aberdeen" },
  { ref: "IAAS-2026-00072", firstName: "Linda", lastName: "Anderson", status: "under_review", debt: 13900, product: "PTD", date: "2026-08-04", ni: "SC324572Z", source: "BASYS", postcode: "DD3 6YZ", email: "linda.anderson@email.co.uk", employment: "employed", confidence: 83, assignedTo: "Sarah Mitchell", city: "Dundee" },
  { ref: "IAAS-2026-00073", firstName: "Craig", lastName: "MacLeod", status: "draft", debt: 5900, product: "Signposting", date: "2026-08-04", ni: "SC435683A", source: "IAAS", postcode: "FK7 7AB", email: "craig.macleod@email.co.uk", employment: "unemployed", confidence: 64, assignedTo: "Unassigned", city: "Falkirk" },
  { ref: "IAAS-2026-00074", firstName: "Patricia", lastName: "Fraser", status: "approved", debt: 20700, product: "DAS", date: "2026-08-05", ni: "SC546784B", source: "eDEN", postcode: "EH16 8CD", email: "patricia.fraser@email.co.uk", employment: "employed", confidence: 93, assignedTo: "Karen MacLeod", city: "Edinburgh" },
  { ref: "IAAS-2026-00075", firstName: "Alistair", lastName: "Ross", status: "submitted", debt: 15400, product: "MAP", date: "2026-08-05", ni: "SC657895C", source: "BASYS", postcode: "G14 9EF", email: "alistair.ross@email.co.uk", employment: "employed", confidence: 85, assignedTo: "Unassigned", city: "Glasgow" },
  { ref: "IAAS-2026-00076", firstName: "Fiona", lastName: "Grant", status: "rejected", debt: 1500, product: "DPP", date: "2026-08-06", ni: "SC768906D", source: "DAS", postcode: "PH1 1GH", email: "fiona.grant@email.co.uk", employment: "retired", confidence: 62, assignedTo: "Unassigned", city: "Perth" },
  { ref: "IAAS-2026-00077", firstName: "Graeme", lastName: "Hamilton", status: "approved", debt: 25100, product: "DAS", date: "2026-08-06", ni: "SC879017E", source: "BASYS", postcode: "IV3 2JK", email: "graeme.hamilton@email.co.uk", employment: "self_employed", confidence: 90, assignedTo: "James Wilson", city: "Inverness" },
  { ref: "IAAS-2026-00078", firstName: "Heather", lastName: "Wallace", status: "additional_info_required", debt: 10200, product: "DAS", date: "2026-08-07", ni: "SC980128F", source: "IAAS", postcode: "KA7 3LM", email: "heather.wallace@email.co.uk", employment: "employed", confidence: 74, assignedTo: "Sarah Mitchell", city: "Kilmarnock" },
  { ref: "IAAS-2026-00079", firstName: "Kenneth", lastName: "Douglas", status: "under_review", debt: 18100, product: "PTD", date: "2026-08-08", ni: "SC091239G", source: "eDEN", postcode: "PA1 4NP", email: "kenneth.douglas@email.co.uk", employment: "employed", confidence: 81, assignedTo: "Karen MacLeod", city: "Paisley" },
  { ref: "IAAS-2026-00080", firstName: "Janet", lastName: "Burns", status: "approved", debt: 34800, product: "Sequestration", date: "2026-08-08", ni: "SC102351H", source: "BASYS", postcode: "KY6 5QR", email: "janet.burns@email.co.uk", employment: "unemployed", confidence: 86, assignedTo: "James Wilson", city: "Dunfermline" },
  { ref: "IAAS-2026-00081", firstName: "Malcolm", lastName: "Scott", status: "submitted", debt: 7600, product: "DAS", date: "2026-08-09", ni: "SC213462J", source: "DAS", postcode: "EH8 6ST", email: "malcolm.scott@email.co.uk", employment: "employed", confidence: 79, assignedTo: "Unassigned", city: "Edinburgh" },
  { ref: "IAAS-2026-00082", firstName: "Eleanor", lastName: "MacKenzie", status: "draft", debt: 4100, product: "Signposting", date: "2026-08-09", ni: "SC324573K", source: "IAAS", postcode: "G22 7UV", email: "eleanor.mackenzie@email.co.uk", employment: "unemployed", confidence: 68, assignedTo: "Unassigned", city: "Glasgow" },
  { ref: "IAAS-2026-00083", firstName: "Iain", lastName: "Sinclair", status: "approved", debt: 16100, product: "MAP", date: "2026-08-10", ni: "SC435684L", source: "eDEN", postcode: "AB22 8WX", email: "iain.sinclair@email.co.uk", employment: "employed", confidence: 92, assignedTo: "Sarah Mitchell", city: "Aberdeen" },
  { ref: "IAAS-2026-00084", firstName: "Diana", lastName: "Reid", status: "under_review", debt: 23900, product: "DAS", date: "2026-08-10", ni: "SC546785M", source: "BASYS", postcode: "DD4 9YZ", email: "diana.reid@email.co.uk", employment: "self_employed", confidence: 76, assignedTo: "Karen MacLeod", city: "Dundee" },
  { ref: "IAAS-2026-00085", firstName: "Robert", lastName: "Patterson", status: "rejected", debt: 2600, product: "Signposting", date: "2026-08-11", ni: "SC657896N", source: "DAS", postcode: "FK8 1AB", email: "robert.patterson@email.co.uk", employment: "retired", confidence: 63, assignedTo: "Unassigned", city: "Falkirk" },
  { ref: "IAAS-2026-00086", firstName: "Nicola", lastName: "Young", status: "approved", debt: 19600, product: "DAS", date: "2026-08-11", ni: "SC768907P", source: "BASYS", postcode: "EH13 2CD", email: "nicola.young@email.co.uk", employment: "employed", confidence: 98, assignedTo: "James Wilson", city: "Edinburgh" },
  { ref: "IAAS-2026-00087", firstName: "Thomas", lastName: "Mitchell", status: "submitted", debt: 11400, product: "PTD", date: "2026-08-12", ni: "SC879018Q", source: "eDEN", postcode: "G33 3EF", email: "thomas.mitchell@email.co.uk", employment: "employed", confidence: 84, assignedTo: "Unassigned", city: "Glasgow" },
  { ref: "IAAS-2026-00088", firstName: "Sheila", lastName: "Clark", status: "additional_info_required", debt: 8400, product: "DAS", date: "2026-08-12", ni: "SC980129R", source: "IAAS", postcode: "PH3 4GH", email: "sheila.clark@email.co.uk", employment: "employed", confidence: 72, assignedTo: "Sarah Mitchell", city: "Perth" },
  { ref: "IAAS-2026-00089", firstName: "Owen", lastName: "Brown", status: "draft", debt: 46000, product: "Sequestration", date: "2026-08-13", ni: "SC091240S", source: "BASYS", postcode: "IV1 5JK", email: "owen.brown@email.co.uk", employment: "unemployed", confidence: 67, assignedTo: "Unassigned", city: "Inverness" },
  { ref: "IAAS-2026-00090", firstName: "Linda", lastName: "MacPherson", status: "approved", debt: 13400, product: "DAS", date: "2026-08-13", ni: "SC102352T", source: "DAS", postcode: "KA8 6LM", email: "linda.macpherson@email.co.uk", employment: "employed", confidence: 91, assignedTo: "Karen MacLeod", city: "Kilmarnock" },
  { ref: "IAAS-2026-00091", firstName: "Craig", lastName: "Duncan", status: "submitted", debt: 6300, product: "MAP", date: "2026-08-14", ni: "SC213463U", source: "BASYS", postcode: "PA2 7NP", email: "craig.duncan@email.co.uk", employment: "unemployed", confidence: 77, assignedTo: "Unassigned", city: "Paisley" },
  { ref: "IAAS-2026-00092", firstName: "Patricia", lastName: "Kerr", status: "rejected", debt: 3100, product: "DPP", date: "2026-08-14", ni: "SC324574V", source: "eDEN", postcode: "KY7 8QR", email: "patricia.kerr@email.co.uk", employment: "employed", confidence: 65, assignedTo: "Unassigned", city: "Dunfermline" },
  { ref: "IAAS-2026-00093", firstName: "Alistair", lastName: "Johnston", status: "approved", debt: 28100, product: "DAS", date: "2026-08-15", ni: "SC435685W", source: "DAS", postcode: "EH17 9ST", email: "alistair.johnston@email.co.uk", employment: "employed", confidence: 87, assignedTo: "James Wilson", city: "Edinburgh" },
  { ref: "IAAS-2026-00094", firstName: "Fiona", lastName: "Morrison", status: "under_review", debt: 15800, product: "PTD", date: "2026-08-15", ni: "SC546786X", source: "BASYS", postcode: "G42 1UV", email: "fiona.morrison@email.co.uk", employment: "self_employed", confidence: 80, assignedTo: "Sarah Mitchell", city: "Glasgow" },
  { ref: "IAAS-2026-00095", firstName: "Graeme", lastName: "Campbell", status: "draft", debt: 9100, product: "MAP", date: "2026-08-16", ni: "SC657897Y", source: "IAAS", postcode: "AB25 2WX", email: "graeme.campbell@email.co.uk", employment: "retired", confidence: 69, assignedTo: "Unassigned", city: "Aberdeen" },
  { ref: "IAAS-2026-00096", firstName: "Heather", lastName: "Stewart", status: "additional_info_required", debt: 20400, product: "DAS", date: "2026-08-16", ni: "SC768908Z", source: "BASYS", postcode: "DD2 3YZ", email: "heather.stewart@email.co.uk", employment: "employed", confidence: 75, assignedTo: "Karen MacLeod", city: "Dundee" },
  { ref: "IAAS-2026-00097", firstName: "Kenneth", lastName: "Murray", status: "submitted", debt: 37200, product: "Sequestration", date: "2026-08-17", ni: "SC879019A", source: "eDEN", postcode: "FK3 4AB", email: "kenneth.murray@email.co.uk", employment: "unemployed", confidence: 73, assignedTo: "Unassigned", city: "Falkirk" },
  { ref: "IAAS-2026-00098", firstName: "Janet", lastName: "MacDonald", status: "approved", debt: 17500, product: "DAS", date: "2026-08-17", ni: "SC980130B", source: "DAS", postcode: "EH1 5CD", email: "janet.macdonald@email.co.uk", employment: "employed", confidence: 94, assignedTo: "James Wilson", city: "Edinburgh" },
  { ref: "IAAS-2026-00099", firstName: "Malcolm", lastName: "Henderson", status: "rejected", debt: 2900, product: "Signposting", date: "2026-08-18", ni: "SC091241C", source: "BASYS", postcode: "G2 6EF", email: "malcolm.henderson@email.co.uk", employment: "unemployed", confidence: 64, assignedTo: "Unassigned", city: "Glasgow" },
  { ref: "IAAS-2026-00100", firstName: "Eleanor", lastName: "Robertson", status: "draft", debt: 12200, product: "DAS", date: "2026-08-19", ni: "SC102353D", source: "IAAS", postcode: "PH1 7GH", email: "eleanor.robertson@email.co.uk", employment: "employed", confidence: 82, assignedTo: "Unassigned", city: "Perth" },

  // The same ten people, misspelled the way four different AiB systems actually
  // hold them, so /search can demonstrate cross-system identity matching against
  // real records rather than describing it. They live in this array rather than a
  // side list because caseStaticParams() derives the static routes from it — a
  // record outside it would render a result row that 404s under output: 'export'.
  //
  // Every spelling here is one human slip from its query and scores 87.5% or
  // better; see nameSimilarity.test.ts. Tempting near-misses were left out on
  // purpose: "Brenda Cambell" and "Elenor Ross" are each two independent edits
  // and land at 78.6%, below the 85% gate the page shows the audience.
  //
  // The Smith cluster carries transposed NI numbers as well as name variants, so
  // the name tile and the NI tile return the same four people.
  { ref: "IAAS-2026-00101", firstName: "John", lastName: "Smith", status: "submitted", debt: 11200, product: "DAS", date: "2026-08-20", ni: "SC129837A", source: "BASYS", postcode: "EH2 4JK", email: "john.smith@email.co.uk", employment: "employed", confidence: 88, assignedTo: "Karen MacLeod", city: "Edinburgh" },
  { ref: "IAAS-2026-00102", firstName: "Jon", lastName: "Smith", status: "under_review", debt: 9400, product: "MAP", date: "2026-08-20", ni: "SC192837A", source: "eDEN", postcode: "G3 7LM", email: "jon.smith@email.co.uk", employment: "employed", confidence: 81, assignedTo: "Sarah Mitchell", city: "Glasgow" },
  { ref: "IAAS-2026-00103", firstName: "John", lastName: "Smyth", status: "approved", debt: 16700, product: "DAS", date: "2026-08-21", ni: "SC129387A", source: "DAS", postcode: "AB11 6NP", email: "john.smyth@email.co.uk", employment: "self_employed", confidence: 79, assignedTo: "James Wilson", city: "Aberdeen" },
  { ref: "IAAS-2026-00104", firstName: "Jhon", lastName: "Smith", status: "additional_info_required", debt: 7300, product: "MAP", date: "2026-08-21", ni: "SC129873A", source: "IAAS", postcode: "DD3 8QR", email: "jhon.smith@email.co.uk", employment: "unemployed", confidence: 68, assignedTo: "Unassigned", city: "Dundee" },
  { ref: "IAAS-2026-00105", firstName: "Ronald", lastName: "Morison", status: "submitted", debt: 13600, product: "PTD", date: "2026-08-22", ni: "SC214968E", source: "eDEN", postcode: "EH4 3ST", email: "ronald.morison@email.co.uk", employment: "employed", confidence: 84, assignedTo: "Unassigned", city: "Edinburgh" },
  { ref: "IAAS-2026-00106", firstName: "Elaine", lastName: "Morrisson", status: "approved", debt: 24800, product: "DAS", date: "2026-08-22", ni: "SC325079F", source: "DAS", postcode: "G5 9UV", email: "elaine.morrisson@email.co.uk", employment: "employed", confidence: 90, assignedTo: "Karen MacLeod", city: "Glasgow" },
  { ref: "IAAS-2026-00107", firstName: "Sarah", lastName: "McDonald", status: "under_review", debt: 5900, product: "Signposting", date: "2026-08-23", ni: "SC436180G", source: "eDEN", postcode: "IV2 4WX", email: "sarah.mcdonald@email.co.uk", employment: "retired", confidence: 72, assignedTo: "Sarah Mitchell", city: "Inverness" },
  { ref: "IAAS-2026-00108", firstName: "Iain", lastName: "MacDonnald", status: "draft", debt: 33400, product: "Sequestration", date: "2026-08-23", ni: "SC547291H", source: "DAS", postcode: "KA2 8YZ", email: "iain.macdonnald@email.co.uk", employment: "unemployed", confidence: 70, assignedTo: "Unassigned", city: "Kilmarnock" },
  { ref: "IAAS-2026-00109", firstName: "Ian", lastName: "Campbel", status: "submitted", debt: 10300, product: "MAP", date: "2026-08-24", ni: "SC658302J", source: "DAS", postcode: "PA3 1AB", email: "ian.campbel@email.co.uk", employment: "employed", confidence: 86, assignedTo: "James Wilson", city: "Paisley" },
  { ref: "IAAS-2026-00110", firstName: "Elleanor", lastName: "Ross", status: "rejected", debt: 2600, product: "DPP", date: "2026-08-24", ni: "SC769413K", source: "eDEN", postcode: "FK2 5CD", email: "elleanor.ross@email.co.uk", employment: "unemployed", confidence: 63, assignedTo: "Unassigned", city: "Falkirk" },
];
